version: "3"
services:
  java_db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=online_shop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - java_db:/var/lib/postgresql/data
      - ./DB/Update_structure.sql:/docker-entrypoint-initdb.d/Update_structure.sql
volumes:
  java_db:
